server:
  port: 8080

spring:
  application:
    name: TestProject
  datasource:
    url: jdbc:postgresql://localhost:5432/testdb
    username: postgres
    password: 78@82!RimZza
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v1/api-docs

